swamplr/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from swamplr_jobs import views
from django.conf import settings

urlpatterns = [
    url(r'^jobs/$', views.job_status, name='jobs'),
    url(r'^$', views.main, name='main'),
    url(r'^admin/', admin.site.urls),
    url(r'^remove/(?P<job_id>[0-9]+)/$', views.remove_job, name='remove_job'),
    url(r'^stop/(?P<job_id>[0-9]+)/$', views.stop_job, name='stop_job'),
    url(r'^job/(?P<job_id>[0-9]+)/$', views.view_job, name='view_job'),
]

if 'swamplr_services' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^services/', include('swamplr_services.urls'))]
if 'swamplr_ingest' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^ingest/', include('swamplr_ingest.urls'))]
if 'swamplr_namespaces' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^namespaces/', include('swamplr_namespaces.urls'))]
if 'swamplr_derivatives' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^derivatives/', include('swamplr_derivatives.urls'))]

swamplr_ingest/urls.py
from django.conf.urls import include, url
from swamplr_ingest import views

urlpatterns = [
    url(r'^([a-z]{1,20})/submit', views.add_ingest_job, name="add-ingest-job"),
    url(r'^manage', views.manage, name="manage-ingest"),
    url(r'^([a-z]{1,20})$', views.run_ingest, name="run-ingest"),
    url(r'^ajax/browse/$', views.browse, name='browse'),
    url(r'^delete/job/(?P<source_job_id>[0-9]+)/$', views.add_delete_job, name='delete-new'),
    url(r'^pathauto/job/(?P<source_job_id>[0-9]+)/$', views.add_pathauto_job, name='pathauto-job'),
]

swamplr_ingest/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class ingest_jobs(models.Model):
    """Information needed to start ingest-specific jobs."""
    ingest_id = models.AutoField(primary_key=True)
    job_id = models.ForeignKey('swamplr_jobs.jobs')
    source_dir = models.CharField(max_length=255)
    # The collection name determines the particular ingest class created for the job.
    collection_name = models.CharField(max_length=255)
    namespace = models.CharField(max_length=255)
    replace_on_duplicate = models.CharField(max_length=1)
    process_new = models.CharField(max_length=1)
    process_existing = models.CharField(max_length=1)
    subset = models.IntegerField(default=0)
    rels_ext_from_file = models.CharField(max_length=1)
    rels_ext_generated = models.CharField(max_length=1)

class delete_jobs(models.Model):
    """Delete objects."""
    delete_id = models.AutoField(primary_key=True)
    job_id = models.ForeignKey('swamplr_jobs.jobs')
    source_job = models.ForeignKey('ingest_jobs')

class delete_objects(models.Model):
    """Each object deleted."""
    object_id = models.AutoField(primary_key=True)
    job_id = models.ForeignKey('swamplr_jobs.jobs')
    # "Success" or "Failure" (or "Skip")
    result_id = models.ForeignKey('object_results')
    pid = models.CharField(max_length=64, null=True)
    deleted = models.DateTimeField(null=True)

class job_datastreams(models.Model):

    job_datastream_id = models.AutoField(primary_key=True)
    ingest_id = models.ForeignKey('ingest_jobs')
    object_type = models.CharField(max_length=32)
    datastream_id = models.ForeignKey('datastreams')

class datastreams(models.Model):
    """Rows for each datastream associated with a given ingest job."""
    datastream_id = models.AutoField(primary_key=True)
    datastream_label = models.CharField(max_length=16)
    # 'y' if a Fedora object, else this is metadata
    is_object = models.CharField(max_length=1)

class job_objects(models.Model):
    """Table to relate filename to PID."""
    object_id = models.AutoField(primary_key=True)
    job_id = models.ForeignKey('swamplr_jobs.jobs')
    created = models.DateTimeField()
    # Filepath
    obj_file = models.CharField(max_length=255, null=True)
    # "Success" or "Failure" (or "Skip")
    result_id = models.ForeignKey('object_results')
    pid = models.CharField(max_length=64, null=True)
    datastream_id = models.ForeignKey('datastreams')
    new_object = models.CharField(max_length=1, null=True)

class object_results(models.Model):

    result_id = models.AutoField(primary_key=True)
    label = models.CharField(max_length=32)

class pathauto_jobs(models.Model):
    """Pathauto job."""
    pathauto_job_id = models.AutoField(primary_key=True)
    job_id = models.ForeignKey('swamplr_jobs.jobs')
    source_job = models.ForeignKey('ingest_jobs')

class pathauto_objects(models.Model):
    """Each object deleted."""
    object_id = models.AutoField(primary_key=True)
    job_id = models.ForeignKey('swamplr_jobs.jobs')
    # "Success" or "Failure" (or "Skip")
    result_id = models.ForeignKey('object_results')
    pid = models.CharField(max_length=64, null=True)
    generated = models.DateTimeField(null=True)

swamplr_ingest/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.db.models import Count
from apps import SwamplrIngestConfig
from models import ingest_jobs, delete_jobs, delete_objects, job_datastreams, datastreams, job_objects, object_results, pathauto_jobs, pathauto_objects
from swamplr_jobs.models import status, job_types, jobs
from collection import CollectionIngest
from forms import IngestForm
from swamplr_jobs.views import add_job, job_status 
from datetime import datetime
from fedora_api.api import FedoraApi
import logging
import sys
import os
import json
from django.conf import settings
from django.db import connections

def manage(request):
    """Manage existing services and add new ones."""
    data = load_manage_data()
    return render(request, 'swamplr_ingest/manage.html', data)


def run_process(current_job):
    """Run process from swamplr_jobs.views."""

    result = None
    # First handle different job types.
    if current_job.type_id.label == "ingest":
        result = process_ingest(current_job)

    elif current_job.type_id.label == "delete":
        result = process_delete(current_job)

    elif current_job.type_id.label == "pathauto":
        result = process_pathauto(current_job)

    return result

def process_ingest(current_job):

    ingest_job = ingest_jobs.objects.get(job_id=current_job)
    collection_defaults = load_collection_defaults()
    collection_data = get_ingest_data(ingest_job.collection_name)

    user_datastreams = []
    for ds in job_datastreams.objects.filter(ingest_id=ingest_job):
        otype = ds.object_type
        user_datastreams.append((ds.datastream_id.datastream_label, otype))
    
    try:
        c = CollectionIngest()
        status_id = c.start_ingest(ingest_job, user_datastreams, collection_data, collection_defaults)
        output = "Ingest complete."

    except Exception as e:
        output = "{0} on line {1} of {2}: {3}".format(type(e).__name__, sys.exc_info()[-1].tb_lineno, os.path.basename(__file__), e)
        status_id = status.objects.get(status="Script error").status_id

    return (status_id, [output])

def process_pathauto(current_job):
    pathauto_job = pathauto_jobs.objects.get(job_id=current_job).source_job.job_id
    objects_to_generate = job_objects.objects.filter(job_id=pathauto_job)
    count = 0
    messages = []
    generated = []
    status_id = None

    try:
        for o in objects_to_generate:
            pid = o.pid
            if pid in generated or pid is None:
                continue
            else:
                generated.append(pid)
            # check if the job is still active (i.e. not cancelled by the user)
            failure_status = jobs.objects.get(job_id=current_job.job_id).status_id.failure
            if failure_status == "manual":
                messages.append("Job manually stopped by user.")
                status_id = status.objects.get(status="Cancelled By User").status_id
                break

            source = "islandora/object/{0}".format(pid)
            alias = "{0}/{1}".format(pid.split(":")[0], pid.split(":")[1])
            with connections['drupal'].cursor() as cursor:
                try:
                    cursor.execute("SELECT alias FROM url_alias WHERE source = %s",[source])
                    record = cursor.fetchone()
                    if record is not None and len(record) == 1:
                        logging.debug("Pauthauto URL already exists for PID: {0}".format(pid))
                    else:
                        logging.info("Creating Pathauto URL for PID: {0}. source: {1}. alias: {2}".format(pid, source, alias))
                        cursor.execute("INSERT INTO url_alias (source, alias, language) VALUES (%s, %s, 'und')", [source, alias])
                    result_id = object_results.objects.get(label="Success")
                except Exception as e:
                    result_id = object_results.objects.get(label="Failure")
                    messages.append("Could not create pathauto URL for {0}. Error: {1}".format(pid, e))
                finally:
                    # Insert into job objects table
                    pathauto_objects.objects.create(
                        job_id=current_job,
                        generated=timezone.now(),
                        result_id=result_id,
                        pid=pid,
                    )
        status_id = status.objects.get(status="Complete").status_id
  
    except Exception as e:
        messages.append("{0} on line {1} of {2}: {3}".format(type(e).__name__, sys.exc_info()[-1].tb_lineno, os.path.basename(__file__), e))
        status_id = status.objects.get(status="Script error").status_id

    return (status_id, messages)

def process_delete(current_job):

    delete_job = delete_jobs.objects.get(job_id=current_job).source_job.job_id
    objects_to_delete = job_objects.objects.filter(job_id=delete_job)
    count = 0
    deleted = []
    skipped = []
    try:
        for o in objects_to_delete:
            if o.new_object: 
                if o.pid not in deleted:
                    response = delete_object(current_job, o.pid)
                    deleted.append(o.pid)
                    if response in [200, 201]:
                        count += 1
                else:
                    pass
            else:
                if o.pid not in skipped:
                    result_id = object_results.objects.get(label="Skipped")

                    delete_objects.objects.create(
                        job_id=current_job,
                        deleted=timezone.now(),
                        result_id=result_id,
                        pid=o.pid,
                        )
                    skipped.append(o.pid)
                else:
                    pass

        status_id = status.objects.get(status="Complete").status_id
        output = "Deleted {0} object(s).".format(count)
    except Exception as e:
        output = "{0} on line {1} of {2}: {3}".format(type(e).__name__, sys.exc_info()[-1].tb_lineno, os.path.basename(__file__), e)
        status_id = status.objects.get(status="Script error").status_id

    return (status_id, [output])

def delete_object(current_job, pid):
    """Delete object by pid."""
    api = FedoraApi(username=settings.GSEARCH_USER, password=settings.GSEARCH_PASSWORD)
    response, output = api.purge_object(pid)
    if response in [200, 201]:
        result = "Success"
    else:
        result = "Failure"
    result_id = object_results.objects.get(label=result)

    delete_objects.objects.create(
        job_id=current_job,
        deleted=timezone.now(),
        result_id=result_id,
        pid=pid,
    )
    return response

def add_ingest_job(request, collection_name):
   
    response = {"error_messages": [],
                "result_messages": [],
                "base_dir": settings.DATA_PATHS,
    }

    collection_data = get_ingest_data(collection_name)

    form = IngestForm(request.POST)
    form.set_fields(collection_name)

    if form.is_valid():
    
        clean = form.cleaned_data
 
        object_datastreams = get_all_datastreams(collection_data, clean)
        metadata_datastreams = get_all_metadata(collection_data, clean)
        all_datastreams = object_datastreams + metadata_datastreams

        # if at least one datastream for the object type (otype) was selected,
        # make sure DC was added as a job_datastream
        counts = {}
        for ds, otype, dtype in all_datastreams:
            if otype in counts:
                counts[otype]["cnt"] = counts[otype]["cnt"] + 1
            else:
                counts[otype] = {}
                counts[otype]["cnt"] = 0
            if ds == "DC":
                counts[otype]["has_dc"] = True

        for obj_type, obj_data in counts.items():
            if "has_dc" not in obj_data:
                all_datastreams.append(("DC", obj_type, "metadata"))        

        process_new = "y" if "process_new" in clean["process"] else ""
        process_existing = "y" if "process_existing" in clean["process"] else ""
        replace_on_duplicate = "y" if clean["replace_on_duplicate"] else ""
        subset = int(clean["subset_value"]) if clean["subset_value"] else 0

        new_job = add_job(SwamplrIngestConfig.name, job_type_label="ingest")
        ingest_job = ingest_jobs.objects.create(
            job_id=new_job,
            source_dir=clean["path_list_selected"],          
            replace_on_duplicate = replace_on_duplicate,
            collection_name=collection_name,
            namespace=clean["pid_namespace"],
            process_new=process_new,
            process_existing=process_existing,
            subset=subset,
        )
        ds_options = datastreams.objects.all()
        existing_ds = [ds.datastream_label for ds in ds_options]
        added = []
        for ds, otype, dtype in all_datastreams:
            if ds not in existing_ds and ds not in added:
                is_object = "y" if dtype == "datastreams" else "" 
                new_ds = datastreams.objects.create(
                    datastream_label=ds,
                    is_object=is_object,
                )
                added.append(ds)

            job_datastream = job_datastreams.objects.create(
                ingest_id=ingest_job,
                object_type=otype,
                datastream_id=datastreams.objects.get(datastream_label=ds),
            )
           
 
    else:

        message = ["Unable to add job: Missing or invalid form data."]
        return run_ingest(request, collection_name, message=message)
 
    return redirect(job_status)

def run_ingest(request, collection_name, message=[]):
   
    form = IngestForm()
    cname = get_ingest_data(collection_name)["label"]
    form.set_fields(collection_name)
    form.set_form_action(collection_name)
    response = {
        "form": form,
        "cname": cname,

swamplr_ingest/templates/swamplr_ingest/browse_helper.html
<script>
$(document).ready(function() {

    $("#div_id_path_list_selected").append('<a role="button" class="btn btn-default browse" data-toggle="modal" data-target="#browse-modal" >Browse</a>');

    //Double click to navigate into the directory
    $('.dir_body').on('dblclick', 'div#lsited_dir', function() {
        var selected_dir = $(this).attr("data-id");
        var back = false
        displayDirectories(selected_dir, back)

    });

    //Single click to select a directory
    $('.dir_body').on('click', 'div#lsited_dir', function() {
        $(".dir").css({
            "border-color": "#e3e3e3",
            "border-width": "1px",
            "border-style": "solid"
        });
        $(".dir").removeClass("selected")
        $(this).css({
            "border-color": "#18453b",
            "border-width": "1px",
            "border-style": "solid"
        })
        $(".select_btn").addClass("select_enable")
        $(this).addClass("selected")
        $(".select_btn").removeClass("select_disable")

    });
    //Single click to navigate back the directory
    $('.dir_body').on('click', 'div#lsited_back_dir', function() {
        var selected_dir = $(this).attr("data-id");
        var back = true
        displayDirectories(selected_dir, back)

    });

    $('.modal-footer').on('click', 'button#modal-sel', function(evt) {
        evt.stopPropagation();
        var selected = $(".selected").attr("data-id");
        $('#id_path_list_selected').val(selected)
        $('#browse-modal').modal('toggle');


    });

    function displayDirectories(selected_dir, back) {
        //Ajax call to views.browse
        //selected_dir(String): Name of the selected directory
        //back(Bool):check if the user is navigating forward or backward
        $.ajax({
            url: '/ingest/ajax/browse/',
            data: {
                'selected_dir': selected_dir,
                'back': back
            },
            dataType: 'json',
            // Ajax call returning a json into the success function
            success: function(data) {
                $(".select_btn").removeClass("select_enable")
                $(".select_btn").addClass("select_disable")
                $(".dir_body").html('')
                // When the user is navigating back and reaches the root dir
                if (data["isRoot"] && back) {
                     $.each(data["base_dirs"], function(key, value) {
                            $(".dir_body").append('<div class = "base_dir  dir list-' + key + ' " id = "lsited_dir" >' + value + '</div>')
                            $(".list-" + key).attr('data-id', value);

                        })
                } else {
                    $(".dir_body").append('<div class = "back_dir  dir back_dir" id = "lsited_back_dir" ><img src = "/static/back-button.png"></div>')
                    $(".back_dir").attr('data-id', data["parent"]);
                    // When the user is navigating forward and there are no child dirs
                    if (data["data"].length == 0) {
                        $(".dir_body").append('<div class = "browse_msg">This folder does not contain any directories </div>')
                    } else {
                        $.each(data["data"], function(key, value) {
                            $(".dir_body").append('<div class = "base_dir  dir list-' + key + ' " id = "lsited_dir" >' + value + '</div>')
                            $(".list-" + key).attr('data-id', value);

                        })

                    }


                }

            }
        });

    }




});
</script>

swamplr_ingest/templates/swamplr_ingest/ingest.html
{% extends "swamplr_jobs/main.html" %}

{% load crispy_forms_tags %}

{% block content %}

{% include "swamplr_ingest/browse_helper.html" %}

<script>
$( document ).ready( function() {
    $( "input[value='DC'].obj-req" ).attr("disabled", "disabled").attr("title", "DC datastream must be selected.");
    $( "input[value='DC']:not(.obj-req)" ).attr("title", "DC datastream will be included if any other datastreams are selected for the object (even if not explicitly checked).");
    $( "#id_process_2" ).change(function() {
       $("#id_replace_on_duplicate").prop('checked', false); 
       $("#div_id_replace_on_duplicate").toggle(200, function() {
        
	});
    });
}); 
</script>
<div class="container-fluid" id="ingest-panel">
    <div class="ingest-heading"><h2>Ingest: <span class="collection-name">{{ cname|title }}</span></h2></div>
    {% crispy form  %}
</div>

{% include "swamplr_ingest/browse_button.html" %}

{% endblock %}

swamplr_ingest/templates/swamplr_ingest/manage.html
{% extends "swamplr_jobs/main.html" %}

{% block content %}


<div class="container-fluid" id="manage-ingest">
    <div class="manage-ingest-heading"><h2>Ingest Configurations</h2></div>
    <p>Changes to ingest settings must currently be made directly on JSON files inside of swamplr. For more information, please refer
       to the <a href="https://github.com/MSU-Libraries/swamplr#ingest-swamplr_ingest">documentation</a>.</p>
    <p>Swamplr is comprised of two configuration files. The first file <b>collection_defaults.json</b> (located at <code>{{ defaults_path }}</code>) includes datastream defaults and content model information corresponding to collection types:</p>
    <div class="json-display"><pre>{{ defaults }}</pre></div>
    <p>The second configuration file, <b>collections.json</b> (located at <code>{{ configs_path }}</code>) should include all collection definitions as well as datastream options to overwrite the values found
       in <code>collection_defaults.json</code>:
    <div class="json-display"><pre>{{ configs }}</pre></div>
</div>

{% endblock %}